version: '3'
services:
    front:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/opt:ro
        networks:
            - default
            - proxy
        labels:
            - traefik.enable=true
            - traefik.frontend.rule=Host:${APP_HOST}
        depends_on:
            - app
            - socket
    app:
        build: .
        user: ${UID}:${GID}
        volumes:
            - .:/opt:rw
    socket:
        image: node:12
        command: ["node", "/opt/socket/server.js"]
        volumes:
            - .:/opt:ro
        expose:
            - 80
        depends_on:
            - redis
    worker:
        image: enyopharma/alignment:7.2
        user: ${UID}:${GID}
        volumes:
            - ./process/alignment.conf:/etc/process.conf:ro
            - .:/opt:rw
        depends_on:
            - redis
    redis:
        image: redis
networks:
    proxy:
        external: true
