version: '3'
services:
    front:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/app:ro
        networks:
            - default
            - proxy
        labels:
            - traefik.enable=true
            - traefik.frontend.rule=Host:${APP_HOST}
        depends_on:
            - app
    socket:
        image: node:12.2.0
        command: ["node", "/app/entrypoints/socket.js"]
        volumes:
            - .:/app:ro
        networks:
            - default
            - proxy
        expose:
            - 80
        depends_on:
            - redis
        labels:
            - traefik.enable=true
            - traefik.frontend.entryPoints=socket
            - traefik.frontend.rule=Host:${APP_HOST}
    app:
        build: .
        user: ${UID}:${GID}
        volumes:
            - .:/app:rw
        networks:
            - default
            - sso
    worker:
        image: enyopharma/alignment:7.2
        user: ${UID}:${GID}
        volumes:
            - .:/app:rw
            - ./process/worker.conf:/etc/process.conf:ro
        depends_on:
            - redis
    redis:
        image: redis
networks:
    proxy:
        external: true
    sso:
        external: true
