version: '3'
services:
    front:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/app:ro
        networks:
            - default
            - web
        environment:
            - VIRTUAL_HOST=${APP_HOST}:80
        depends_on:
            - app
    app:
        build: .
        user: ${UID}:${GID}
        volumes:
            - .:/app:rw
        networks:
            - default
            - sso
    queue:
        build: .
        user: ${UID}:${GID}
        volumes:
            - .:/app:rw
        command: php entrypoints/worker.php
        networks:
            - default
        depends_on:
            - redis
    redis:
        container_name: drakkar_redis
        image: redis
networks:
    web:
        external:
            name: enyo_proxy
    sso:
        external:
            name: enyo_sso
