version: '3'
services:
    frontend:
        build: ./frontend
        depends_on:
            - app
            - socket
    app:
        build: ./app
        environment:
            - APP_ENV=development
            - APP_DEBUG=true
            - DB_HOSTNAME=host.docker.internal
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_PORT=${DB_PORT}
            - REDIS_SCHEME=${REDIS_SCHEME}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - SCIHUB_HOST=${SCIHUB_HOST}
        extra_hosts:
            - host.docker.internal:host-gateway
    socket:
        build: ./socket
        depends_on:
            - redis
        environment:
            - REDIS_SCHEME=${REDIS_SCHEME}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
    alignment:
        build: ./workers/alignment
        depends_on:
            - redis
        environment:
            - REDIS_SCHEME=${REDIS_SCHEME}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
    redis:
        image: redis
