version: '3'
services:
    front:
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./app:/var/www/html:ro
        networks:
            - default
            - proxy
        labels:
            - traefik.http.routers.drakkar.rule=Host(`${APP_HOST}`)
    app:
        user: ${UID}:${GID}
        volumes:
            - ./app:/var/www/html:rw
    alignment:
        user: ${UID}:${GID}
        volumes:
            - ./workers/alignment/process.conf:/etc/process.conf:ro
            - ./app:/opt:rw
networks:
    proxy:
        external: true
