version: '3'
services:
    frontend:
        ports:
            - 8000:80
        volumes:
            - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./app:/var/www/html:ro
    app:
        user: ${UID}:${GID}
        volumes:
            - ./app:/var/www/html:rw
    socket:
        volumes:
            - ./socket:/var/www/html:ro
    alignment:
        volumes:
            - ./workers/alignment:/opt/workers/alignment:ro
