version: '3'
services:
    front:
        build: .
        depends_on:
            - app
            - socket
    app:
        build: ./app
        environment:
            - APP_HOST=${APP_HOST}
            - SSO_HOST=${SSO_HOST}
            - DB_HOSTNAME=${DB_HOSTNAME}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_PORT=${DB_PORT}
            - REDIS_SCHEME=${REDIS_SCHEME}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
    socket:
        build: ./socket
        depends_on:
            - redis
        environment:
            - REDIS_SCHEME=${REDIS_SCHEME}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
    alignment:
        build: workers/alignment
        depends_on:
            - redis
        environment:
            - REDIS_SCHEME=${REDIS_SCHEME}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
    redis:
        image: redis
