version: '3'
services:
    frontend:
        volumes:
            - app:/var/www/html:ro
        networks:
            - default
            - proxy
        labels:
            - traefik.http.routers.drakkar.rule=Host(`${APP_HOST}`)
    app:
        volumes:
            - app:/var/www/html:rw
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
volumes:
    app:
networks:
    proxy:
        external: true
