version: '3'
services:
    front:
        ports:
            - 80:80
        volumes:
            - app:/var/www/html:ro
    app:
        volumes:
            - app:/var/www/html:rw
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
    alignment:
        volumes:
            - app:/opt:rw
volumes:
    app:
